#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

info () {
  # Print an info message
  printf "[\033[00;34m INFO \033[0m] $1\n"
}

okay () {
  # Print a success message
  printf "[\033[00;32m OKAY \033[0m] $1\n"
}

echo ""
info "Starting pre-push hooks..."

info "Running TypeScript check..."
npx tsc --noEmit

echo ""
info "Running Unit Tests"
npm run test -- --watchAll false --bail

echo ""
okay "All checks successful."
echo ""
