name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
      - run: npm run lint
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
      - run: npm run test:cov
  build:
    runs-on: ubuntu-latest
    needs: [lint, unit-test]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - run: npm ci
      - run: npm run build
      - if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: game-build
          path: dist
  playwright:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
          cache: "npm"
      - uses: actions/download-artifact@v2
        with:
          name: game-build
          path: dist
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npm run playwright -- --browser=all
      - if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: playwright-results
          path: test-results
